### ISSUE TITLE
Instead of Gemify, selling the items

### ISSUE THREAD

**Issue by Rysanlos** [timvandam/gemify#1]
Hello, I have a udge inventory, and gemify my cards it's not benifical at all.
I'm suggesting to have an option we can sell the items to the marked of the community.
Using the price of the market and add the possibility to reduce the default value (by exemple a card cost 0.05 in the community market, I want to sell it for -0.01 so selling it at 0.04).

Also, add a confirmation button every 250 listed items (it's the limite to confirm the listing with 2fa)
So the bot sell 250 items, he stop, we confirming with 2fa, and then we press continue, and the bot sells the next 250, etc...
Please it's will be a great feature to bulk sells the items instead of gemify them (not benefical at all)

**Comment by timvandam** [comment]
I will not be making anything like this as it is against the subscriber agreement you agree to when you use Steam. I am open to other ideas though, just make sure that Steam allows it.

**Comment by Rysanlos** [comment]
When you go on steam badge page with cards on steam, there is buttons to mass sell cards, but it's per badge, so I think it's not against the ToS.

**Comment by timvandam** [comment]
That's not how it works, terms are terms, you can't reason your way around them.

Per the subscriber agreement:
"You may not use Cheats, automation software (bots), mods, hacks, or any other unauthorized third-party software, to modify or automate any Subscription Marketplace process."
